/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello.world.kotlin

class App {
    fun greeting(): String {
        return "Hello World!"
    }
}

fun main() {
    println(App().greeting())
}
